version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "Dependencies 📦"
          - "PHP 🐘"
      versioning-strategy: "increase-if-necessary"
      open-pull-requests-limit: 1
