version: '3.2'
services:
  postgres:
    container_name: clair_postgres
    # This image provides a nightly build with updated vulnerability databases
    # once setting up clair from scratch can take up to 30 minutes
    image: arminc/clair-db:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: arminc/clair-local-scan:v2.0.4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
