filter:
    paths: [src/*]
    excluded_paths: [examples/*, tests/*]
tools:
    external_code_coverage: true
    php_analyzer: true
    php_hhvm: true
    php_sim: true
    php_pdepend: true
    sensiolabs_security_checker: true
    php_changetracking: true
    php_code_sniffer:
        enabled: true
        config:
            tab_width: 0
            encoding: utf8
            ruleset: ~
            standard: "PSR2"
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
    php_mess_detector:
        enabled: true
        config:
            ruleset:              ~
            code_size_rules:
                cyclomatic_complexity: true
                npath_complexity: true
                excessive_method_length: true
                excessive_class_length: true
                excessive_parameter_list: true
                excessive_public_count: true
                too_many_fields: true
                too_many_methods: true
                excessive_class_complexity: true
            design_rules:
                exit_expression: true
                eval_expression: true
                goto_statement: true
                number_of_class_children: true
                depth_of_inheritance: true
                coupling_between_objects: true
            unused_code_rules:
                unused_private_field: true
                unused_local_variable: true
                unused_private_method: true
                unused_formal_parameter: true
            naming_rules:
                short_variable:
                    minimum: 3
                long_variable:
                    maximum: 20
                short_method:
                    minimum: 3
                constructor_conflict: true
                constant_naming: true
                boolean_method_name: true
            controversial_rules:
                superglobals: true
                camel_case_class_name: true
                camel_case_property_name: true
                camel_case_method_name: true
                camel_case_parameter_name: true
                camel_case_variable_name: true
checks:
    php:
        code_rating: true
