FROM composer:2 AS runtime

RUN mkdir /workdir
COPY next.php /workdir
RUN mkdir /workdir/src
COPY src/ /workdir/src
COPY ./composer.json /workdir
COPY ./composer.lock /workdir
WORKDIR /workdir

RUN composer install --ansi --no-progress --no-interaction --prefer-dist --no-dev

ENTRYPOINT ["php", "/workdir/next.php"]
